// Generated by CoffeeScript 1.7.1
bz.initGui = function() {
  var mag_sider, vac_slider;
  mag_sider = new bz.Slider(game, {
    pos: xy(100, 300),
    length: 200,
    orientation: 'v',
    label: "MAGNETIC FIELD"
  });
  return vac_slider = new bz.Slider(game, {
    pos: xy(300, 300),
    length: 200,
    orientation: 'v',
    label: "VACUUM SPEED"
  });
};
